name: Hello World
author: Yomi
description: Hello action
inputs:
  who-to-greet:
    description: "who to greet"
    required: true
    default: Yomi
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node16"
  main: "./dist/index.js"
